# -*- coding: utf-8 -*-
{
    'name': "Cotizador",
    'summary': "Cotizador de productos",
    'description': """
Long description of module's purpose
    """,
    'author': "OBI",
    'website': "https://www.obi-mx.com/es_MX",
    'category': 'Uncategorized',
    'version': '1.0',
    'depends': ['base', 'mail','product','mrp','project', 'product_unspsc', 'sale', 'crm'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        # --- Carga de datos iniciales ---
        # 'data/ir_sequence_data.xml',
        # 'data/site_data.xml',               
        # 'data/unit_of_measure_data.xml',   
        # 'data/cost_type_data.xml',       
        # 'data/product_type_data.xml',      
        # 'data/range_template_data.xml',    
        # 'data/project_data.xml',    
        # 'data/config_parameter_data.xml',
        # 'data/printer_data.xml',           
        # 'data/type_item_data.xml',          
        # 'data/item_data.xml',         
        # 'data/item_template_data.xml', 
        # 'data/type_printing_data.xml',     
        # --- Vistas ---
        'data/ir_sequence_data.xml',
        'views/product_views.xml',
        'views/product_type_views.xml',
        'views/by_product_views.xml',
        'views/types_of_printing_views.xml',
        'views/client_views.xml',
        'views/product_finish_views.xml',
        'views/unit_of_measure_views.xml',
        'views/item_type_views.xml',
        'views/item_template_views.xml',
        'views/site_views.xml',
        'views/costs_views.xml',
        'views/range_template_views.xml',
        'views/item_by_product_views.xml',
        'views/printer_views.xml',
        'views/list_of_materials_views.xml',
        'views/material_by_product_views.xml',
        'views/item_views.xml',
        'views/product_design_views.xml',
        'views/product_design_stages_views.xml',
        'reports/report_quotation_template_ibs.xml',
        'views/byproduct_item_type_views.xml',
        'views/byproduct_item_views.xml',
        'views/cost_type_views.xml',
        'views/byproduct_item_line_views.xml',
        'views/byproduct_material_list_views.xml',
        'views/finishing_templates.xml',
        'views/processes_views.xml',
        'views/dummies_views.xml',
        'views/lines_operations_views.xml',
        'views/product_category_view.xml',
        'views/crm_lead_view.xml',
        'views/menus_views.xml',
    ],
    'application': True,
    'installable': True,
}
